services:
  marketflow:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    container_name: marketflow
    depends_on:
      - postgres//
      - redis
      - exchange1
      - exchange2
      - exchange3
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=marketflow
      - REDIS_ADDR=redis:6379
      - MODE=live

  # PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: marketflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  # Эмуляторы бирж
  exchange1:
    image: exchange1:latest
    container_name: exchange1
    ports:
      - "40101:40101"

  exchange2:
    image: exchange2:latest
    container_name: exchange2
    ports:
      - "40102:40102"

  exchange3:
    image: exchange3:latest
    container_name: exchange3
    ports:
      - "40103:40103"

volumes:
  pgdata:
