services:
  marketflow:
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    container_name: marketflow
    depends_on:
      - postgres
      - redis
      - exchange1
      - exchange2
      - exchange3
    ports:
      - "${API_ADDR:-8080}:8080"
    environment:
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB}
      - MODE=live

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "${PG_PORT}:${PG_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  exchange1:
    image: ${EXCHANGE1_NAME}:latest
    container_name: ${EXCHANGE1_NAME}
    ports:
      - "${EXCHANGE1_PORT}:${EXCHANGE1_PORT}"
    environment:
    - EXCHANGE1_ADDR=${EXCHANGE1_NAME}:${EXCHANGE1_PORT}

  exchange2:
    image: ${EXCHANGE2_NAME}:latest
    container_name: ${EXCHANGE2_NAME}
    ports:
      - "${EXCHANGE2_PORT}:${EXCHANGE2_PORT}"
    environment:
    - EXCHANGE2_ADDR=${EXCHANGE2_NAME}:${EXCHANGE2_PORT}

  exchange3:
    image: ${EXCHANGE3_NAME}:latest
    container_name: ${EXCHANGE3_NAME}
    ports:
      - "${EXCHANGE3_PORT}:${EXCHANGE3_PORT}"
    environment:
    - EXCHANGE3_ADDR=${EXCHANGE3_NAME}:${EXCHANGE3_PORT}

volumes:
  pgdata:
